apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poam
  name: poam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poam
  template:
    metadata:
      labels:
        app: poam
    spec:
      containers:
      - image: panurag1/core-app-image
        name: core-app-image
        imagePullPolicy: Always
        ports:
          - containerPort: 80